[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
  
[tool.yapf]
based_on_style = "google"
split_before_first_argument = true
column_limit = 100
blank_line_before_nested_class_or_def = true
coalesce_brackets = true
arithmetic_precedence_indication = true

[tool.isort]
line_length = 100
