[metadata]
name = eggman
version = 0.35
author = Daniel Thorngren
author_email = dpthorngren@gmail.com
description = "Code for calculating the geometry and transit depths of piecewise ellipsoidal objects.",
url = "https://github.com/dpthorngren/Eggman"
long_description = file: README.md
license = MIT
github_project = dpthorngren/Eggman

[options]
packages = eggman
package_dir =
    =src

install_requires =
    setuptools ; python_version > "3.11"
    numpy
    cython

[options.package_data]
* = cy_eggman.pxd

[options.extras_require]
develop =
    pytest
    cython-lint
    pytest-cov
