version: 3


tasks:
  default:
    deps: [test]

  devbuild:
    desc: "Rebuild shared library (if cython files have changed) and reinstall."
    deps: [lint]
    run: once
    sources:
      - src/eggman/*.pyx
      - src/eggman/*.pxd
      - src/cpp_source/[a-z_]*.cpp
      - src/include/[a-z_]*.hpp
    generates:
      - src/eggman/*.so
      - src/eggman/cy_*.cpp
    cmds:
      - rm -rf build eggman.egg-info src/eggman/*.so
      - pip uninstall eggman --yes
      - pip install --no-build-isolation -e .[develop]

  lint:
    desc: "Run cython linter"
    run: once
    cmds:
      - flake8 ./*.py ./src/eggman/*.py --count --show-source --statistics # $(git ls-tree -r HEAD --name-only | grep '.*py$') --count --show-source --statistics
      - cython-lint .

  test:
    deps: [lint, devbuild]
    desc: "Run pytest."
    cmds:
      - pytest -x

  experiment:
    deps: [lint, devbuild]
    desc: "Run experiments file, bypassing pytest."
    cmds:
      - python experiment.py
