# This file was generated by stubgen-pyx v0.2.17 from src/eggman/cy_eggman.pyx

from typing import Optional, TypeAlias, TypedDict

import cython
import numpy
import numpy as np
import numpy.typing
from cython.cimports.eggman import cy_eggman as cye

SourceType: TypeAlias = int
Array1d_f64: TypeAlias = numpy.typing.NDArray[numpy.double]
Array2d_f64: TypeAlias = numpy.typing.NDArray[numpy.double]
Array_SourceParams: TypeAlias = float[object]

@cython.cclass
class Orbit:
    """Describes an orbit so that the position at a given time may be calculated.

    This class wraps the C++ class Orbit, plus solve_kepler as a static function."""
    corbit: cye.COrbit

    @property
    def period(self) -> float:
        """The orbital period."""
    @property
    def semimajor(self) -> float:
        """The orbital semimajor axis."""
    @property
    def eccen(self) -> float:
        """The orbital eccentricity."""
    @property
    def cos_inc(self) -> float:
        """The cosine of the inclination, which is useful for orienting objects along their orbits."""
    def __init__(self, period: float, t0: float, semimajor: float, eccen: float=0, inclination: float=90, lon_periapse: float=90):
        """Initialize an orbit object with the given orbital elements.

        Args:
            period: The orbital period.  Any unit may be used so long as it is used consistently.
            t0: The epoch time, when the orbit passes x=0 in the positive direction; same units as period.
            semimajor: The orbital semimajor axis.  Any unit may be used, but this sets the output units of
                the get_position function.  Usually users will wish to use units of stellar radius.
            eccen: The orbital eccentricity, it must be positive and less than 1, as this object cannot
                work with unbound orbits.
            inclination: The orbital inclination in degrees.  90 is an edge-on orbit, so transiting planets
                will typically be near this. i=0 is a clockwise orbit, starting from [0, a, 0] at t=0.
            lon_periapse: The longitude of the orbit's periapse.  A value of 90 places the periapse at
                [-a*(1-e), 0., 0.].
        """
    def get_position(self, t: float):
        """Calculates the position of the orbiting object at a given time.

        Args:
            t: The time to get the orbital position for.  The units must be the same as those used for
                `period` and `t0` on initialization.

        Returns:
            The position of the orbiting object at time t, as a one-dimensional numpy array of size 3.
        """
    @staticmethod
    def solve_kepler(mean_anomaly: float, eccen: float):
        """Solves the kepler equation for the true anomaly given the mean anomaly and eccentricity."""

@cython.cclass
class Shape:
    """A wrapper class for the C++ class Biellipsoid, with some added convenience functions.

    The biellipsoid consists of two tri-axial ellipsoids which share radii along the y and z axis
    but not necessarily the x axis, which are joined along the y-z plane, rotated arbitrarily, and
    then shifted to some position.

    For these calculations, three reference frames are used -- the conversion functions are exposed
    fmainly for debugging purposes.  The frames are:
        :View Frame: This is the native frame users will be operating in. It is easiest to think of
            +x as being "right", +y as "up", and +z as "towards the viewer".
        :Aligned Frame: This is the frame in which the forward vector points in the +x,
            the up vector points in the +y, and the side vector points in the +z directions.  The
            rotation matrix of the biellipsoid rotates points from this frame to the view frame.
        :Sphere Frame: In this frame, the biellipsoid is a unit sphere.  This is a non-linear
            transform from the aligned frame, scaling y and z by r_up and r_side respectively,
            and x by r_forward or r_backward depending on whether x > 0.  Many geometric
            calculations amount to transforming to this frame, finding some point, line, or plane,
            and then transforming back to the view space.
    """
    cshape: cye.CShape

    @property
    def r_forward(self):
        """The forward radius of the object; the +x direction for an identity rotation matrix."""
    @property
    def r_back(self):
        """The forward radius of the object; the -x direction for an identity rotation matrix."""
    @property
    def r_up(self):
        """The upward radius of the object; the y axis for an identity rotation matrix."""
    @property
    def r_side(self):
        """The upward radius of the object; the z axis for an identity rotation matrix."""
    @property
    def position(self):
        """The position of the center of the biellipsoid, as a numpy array."""
    @property
    def radii(self):
        """The forward, backward, up, and side radii of the bielipsoid, as a numpy array."""
    @property
    def rot(self):
        """The rotation matrix of the biellipsoid, a 3x3 numpy array, which transforms points
        from aligned to view space."""
    @property
    def forward(self):
        """The forward vector in view space."""
    @property
    def up(self):
        """The biellipsoid's up (along the poles) vector in view space."""
    @property
    def side(self):
        """The biellipsoid's side (forward cross up) vector in view space."""
    @property
    def limb_forward(self):
        """The ellipse defining the limb (visible edge) of the Biellipsoid on its forward half."""
    @property
    def limb_back(self):
        """The ellipse defining the limb (visible edge) of the Biellipsoid on its back half."""
    @property
    def joint(self):
        """The ellipse around the surface of the planet within the plane that joins the two
        half-ellipsoids that make up the biellipsoid."""
    def __init__(self, r_forward: float, r_back: float, r_up: float, r_side: float, theta: float=0, phi: float=0, gamma: float=0, ci: float=-2, x: float=0, y: float=0, z: float=0):
        """Define a biellipsoid in terms of it's origin position, rotation angles, and radii.

        Args:
            r_forward: The forward radius of the object -- along the +x direction for an identity
                rotation matrix.
            r_back: The forward radius of the object -- along the -x direction for an identity
                rotation matrix.
            r_up: The upward radius of the object -- along the y axis for an identity rotation
                matrix.
            r_side: The upward radius of the object -- along the z axis for an identity rotation
                matrix.
            theta: The counter-clockwise rotation of the biellipsoid around the z axis.
            phi: The counter-clockwise rotation of the biellipsoid around the y axis.
            gamma: The counter-clockwise rotation of the biellipsoid around the x axis.
            ci: The cosine of the inclination of the orbit.  This is used only to reorient the
                object along its orbit at the current position.  If the object should not be
                rotated with its current position, set as -2.
            x: The x position of the biellipsoid, in view space.
            y: The y position of the biellipsoid, in view space.
            z: The z position of the biellipsoid, in view space.
        """
    def set_rotation(self, theta: float, phi: float, gamma: float, ci: float=-2):
        """Sets the rotation of the biellipsoid to the new given values. The first three arguments
            are Euler angles around the z, y, and x axes respectively, applied in reverse order.
            If the final argument is between 0 and 1, the biellipsoid will further be rotated
            along its orbit.

        Args:
            theta: The counter-clockwise rotation of the biellipsoid around the z axis.
            phi: The counter-clockwise rotation of the biellipsoid around the y axis.
            gamma: The counter-clockwise rotation of the biellipsoid around the x axis.
            ci: The cosine of the inclination of the orbit.  This is used only to reorient the
                object along its orbit at the current position.  If the object should not be
                rotated with its current position, set as -2."""
    def set_position(self, x: float, y: float, z: float):
        """Set the position of the biellipsoid.  Note that this will not update the rotation of
        the object with its orbit; if this is desired, users should call set_rotation next."""
    def is_visible(self, x: float, y: float, z: float):
        """Determines whether a the given point is 'visible' from the view plane; that is, whether
        a straight ray from the given point extending in the -z direction does NOT pass through
        the biellipsoid."""
    def is_forward(self, x: float, y: float, z: float):
        """Determines whether a point is on the forward half of the biellipsoid or the backwards
        half.  The point does not need to be on the surface of the biellipsoid, as it will be
        compared against the joining plane."""
    def is_forward_2d(self, x: float, y: float, local: cython.bint=False):
        """Determines whether the point closest to the viewer (lowest z) on the surface of the
        biellipsoid at [x, y] is on the forward half of the biellipsoid or the backwards half.
        This is similar to `is_forward` but is faster than using raycast to find the
        intersection point and subsequently call is_forward.

        Returns false if there are no points on the Biellipsoid at [x, y]."""
    def x_bounds(self):
        """Returns the maximum and minimum extent of the biellipsoid in the x direction."""
    def y_bounds(self):
        """Returns the maximum and minimum extent of the biellipsoid in the y direction."""
    def slice_ylimits(self, x: float):
        """For a given x, returns the largest and smallest values of y for which there is some z
        such that [x, y, z] is on the biellipsoid.  This is useful for computing integrals in
        view-space."""
    def line_intersects(self, x, y):
        """Determines whether the line passing through [x, y, 0] in the +/-z direction passes
        through the biellipsoid."""
    def raycast(self, x: float, y: float): ...
    def world_to_aligned(self, loc): ...
    def world_to_sphere(self, loc): ...
    def aligned_to_world(self, loc): ...
    def aligned_to_sphere(self, loc): ...
    def sphere_to_world(self, loc): ...
    def sphere_to_aligned(self, loc): ...
    def principal_axes(self):
        """Get the principle axes from a biellipsoid, for visualization and testing purposes."""
    def meridians(self, axis=0, res=200):
        """Get the positions of the equator and 90-degree meridians on the biellipsoid."""
    def outline(self, res=200, yrange=False): ...
    def plot_ellipses(self, res=200, method='angles', f_args=dict(), b_args=dict()):
        """Similar to plot_outline, but plots each ellipse that makes up the bielipsoid's limb
        separately (including on the other ellipse's side), for debugging visualization purposes."""
    def plot_axes(self, colors=None, **args): ...
    def plot_outline(self, res=200, **args): ...
    def plot_area(self, res=200, **args): ...
    def plot_meridians(self, res=200, eq_args=dict(), prime_args=dict(), front_args=dict(), visible_only=True): ...

@cython.cclass
class LightSource:
    csource: cye.LightSource
    _source_type_names_ = ['no_emission', 'lambertian', 'quadratic_limb', 'nonlinear_limb', 'day_night']
    _source_n_params_ = [0, 1, 3, 5, 2]
    _source_enum_ = [SourceType.NoEmission, cye.SourceType.Lambertian, cye.SourceType.QuadraticLimb, cye.SourceType.NonLinearLimb, cye.SourceType.DayNight]

    @property
    def source_type(self): ...
    @property
    def source_type_code(self): ...
    @property
    def source_params(self): ...
    @property
    def limb_norm(self): ...
    def __init__(self, source_type: str, source_params: list[float]): ...
    def get_brightness(self, x, y, bell: Shape): ...
    def get_brightness_sphere(self, x, y): ...
    def plot_brightness(self, shp: Shape, res=400, axis=None, **args): ...

@cython.cclass
class Ellipse:
    @property
    def e1(self): ...
    @property
    def e2(self): ...
    @property
    def det(self): ...
    @property
    def x_size(self): ...
    @property
    def y_size(self): ...
    def __init__(self, e1, e2): ...
    @classmethod
    def create_from_rot_radii(cls, a: float, b: float, rot: np.ndarray): ...
    def get_ybounds(self, x: float): ...
    def line_intersects(self, x: float, y: float) -> tuple[cython.bint, np.ndarray]: ...
    def nearest_to_line(self, xt: float, yt: float): ...
    def outline(self, res=200, dir: Optional[np.ndarray] | None=None, method: str='angles'): ...
    def plot_outline(self, res=200, origin=(0.0, 0.0), dir=None, method='angles', **args): ...
    def plot_vectors(self, origin=(0.0, 0.0), **args): ...

@cython.cclass
class PlanetSystem:
    cps: cye.CPlanetSystem

    def __init__(self, atol=1e-06, rtol=0.001):
        """Initialize a PlanetSystem with the integration tolerances.

        Args:
            atol: the absolute tolerance for the integrators.
            rtol: the tolerance for the integrators relative to the result."""
    def add_object(self, orbit: Orbit, shape: Shape, source: LightSource, rotate_with_orbit: cython.bint=False, parent_index: int=-1):
        """Adds an object of the given specifications to the system.

        Args:
            orbit: An Orbit object describing the orbit of the object being added.
            shape: A Shape object describing the shape of the object being added.
            source: A LightSource object describing the emission of the object.
            rotate_with_orbit: whether or not the object rotates as it moves through its orbit
                (tidally locked to the parent or origin).
            parent_index: The index of a previously added object that the new object should orbit
                (like a moon); if negative, the new object orbits the origin.
        """
    def add_planet(self, r_forward: float, r_back: float, r_up: float, r_side: float, period: float, semimajor: float, t0: float=0, eccen: float=0, inclination: float=90, lon_periapse: float=90.0, theta: float=0, phi: float=0, gamma: float=0, source: LightSource | None=None, rotate_with_orbit: cython.bint=True, parent_index: int=-1):
        """Adds a planet of the given specifications to the system.  This is a wrapper for
            add_object, whose arguments are passed through to Shape and Orbit.

        Args:
            r_forward: The forward radius of the object -- along the +x direction for an identity
                rotation matrix.
            r_back: The forward radius of the object -- along the -x direction for an identity
                rotation matrix.
            r_up: The upward radius of the object -- along the y axis for an identity rotation
                matrix.
            r_side: The upward radius of the object -- along the z axis for an identity rotation
                matrix.
            period: The orbital period.  Any unit may be used so long as it is used consistently.
            semimajor: The orbital semimajor axis.  Any unit may be used, but this sets the output
                units of the get_position function.  Usually users will wish to use units of
                stellar radius.
            t0: The epoch time, when the orbit passes x=0 in the positive direction; must have the
                same units as period.
            eccen: The orbital eccentricity, it must be positive and less than 1, as this object
                cannot work with unbound orbits.
            inclination: The orbital inclination in degrees.  90 is an edge-on orbit, so transiting
                planets will typically be near this. i=0 is a clockwise orbit, starting from
                [0, a, 0] at t=0.
            lon_periapse: The longitude of the orbit's periapse.  A value of 90 places the periapse
                at [-a*(1-e), 0., 0.].
            theta: The counter-clockwise rotation of the biellipsoid around the z axis.
            phi: The counter-clockwise rotation of the biellipsoid around the y axis.
            gamma: The counter-clockwise rotation of the biellipsoid around the x axis.
            source: A LightSource object describing the emission of the object.
            rotate_with_orbit: whether or not the object rotates as it moves through its orbit
                (tidally locked to the parent or origin).
            parent_index: The index of a previously added object that the new object should orbit
                (like a moon); if negative, the new object orbits the origin."""
    def add_star(self, limb_type: str, limb_params: list[float]):
        """Adds a star to the system.  This is a wrapper for add_object, and places a unit-sphere
            at the origin.

        Args:
            limb_type: A string indicating the type of limb darkening of the star.  Should be one
                of "lambertian" (flat), "quadratic_limb", or "nonlinear_limb".
            limb_params: A list of floats representing the parameters of the limb darkening, whose
                length depends on the limb type (0, 2, and 4 respectively from the above list).  If
                provided, an additional parameter at the start sets the overall brightness
                (1/pi results in a total luminosity of 1, and so is the default)."""
    def set_time(self, t: float) -> None:
        """Sets the time of the system, moving the objects into position based on their orbits.
            This is automatically called in phase_curve_integral but can be useful for debugging
            and with plot_objects.

        Args:
            t: the time, in the same units as the period and epoch time t0 specified in the Orbit
                objects."""
    def integrate_single(self, i: int) -> float:
        """Get the brightness of a single target at the current time (set by set_time,
            defaulted to 0.)

        Args:
            i: Which object to get the brightness of -- these are indexed increasing from 0 in
                order of insertion."""
    def phase_curve_integral(self, times: cye.Array1d_f64):
        """Get the brightness of all objects in the system, added together, at the given times.
            This is the standard function to call for getting a light curve.

        Args:
            times: A numpy array of times to calculate for, in the same units as periods and epoch
                time t0 specified in the orbits.

        Returns:
            A Numpy array of brightnesses at the specified times."""
    def get_n_objects(self) -> int:
        """Returns the number of objects that have been successfully inserted so far."""
    def clear_objects(self) -> None:
        """Deletes all the objects so far added, starting over from scratch.  This is slightly
        faster than creating a new object."""
    def __getitem__(self, i: int) -> tuple[Orbit, Shape, LightSource, bool]:
        """Get an object previously added to the system.

        Args:
            i: The index of the object, which were set in order of insertion starting from 0.

        Returns:
            A tuple of an OrbitWrap, Shape, LightSource, and bool object that describing the i'th
                object -- the final bool is whether the object rotates with its orbit.
        """
    def plot_objects(self, res=200, axis=None, arg_list=list(), **args):
        """Create a simple plot of the system using matplotlib, at the current time (set by
            set_time or 0 by default), using matplotlib.pcolormesh.

        Args:
            res: The resolution to plot the objects at, as an integer.
            axis: The matplotlib axis object to plot on.  If left as the default None, new axes
                will be created.
            arg_list: A list of dictionaries containing keyword arguments to pass to
                pyplot.pcolormesh. for each object in the system in order.  These settings override
                global settings from **args.
            **args: Additional keyword arguments to be passed to pyplot.pcolormesh for all objects
                in the system, unless overridden by arg_list."""

class Mat3(TypedDict):
    xx: float
    xy: float
    xz: float
    yx: float
    yy: float
    yz: float
    zx: float
    zy: float
    zz: float

class Vec3(TypedDict):
    x: float
    y: float
    z: float

class Bounds(TypedDict):
    min: float
    max: float

def transit(r_forward: float, r_back: float, r_up: float, r_side: float, theta: float, phi: float, gamma: float, t: numpy.typing.NDArray[numpy.double], t0: float, period: float, semimajor: float, inclination: float, source_type: str, source_params: object, eccen: float=0, lon_periapse: float=90, rotate_with_orbit: bool=True, atol: float=1e-06, rtol: float=0.001) -> object:
    """Wrapper for the c function transit3d_integral"""
