# This file was generated by stubgen-pyx v0.2.17 from src/eggman/cy_eggman.pyx

import typing
from typing import Optional, TypeAlias, TypedDict

import cython
import numpy
import numpy as np
import numpy.typing
from cython.cimports.eggman import cy_eggman as cye

SourceType: TypeAlias = int
Array1d_f64: TypeAlias = numpy.typing.NDArray[numpy.double]
Array2d_f64: TypeAlias = numpy.typing.NDArray[numpy.double]
Array_SourceParams: TypeAlias = float[object]

@cython.cclass
class Orbit:
    """Describes an orbit so that the position at a given time may be calculated.

    This class wraps the C++ class Orbit, plus solve_kepler as a static function."""
    corbit: cye.COrbit

    @property
    def period(self) -> float:
        """The orbital period."""
    @property
    def semimajor(self) -> float:
        """The orbital semimajor axis."""
    @property
    def eccen(self) -> float:
        """The orbital eccentricity."""
    @property
    def cos_inc(self) -> float:
        """The cosine of the inclination, which is useful for orienting objects along their orbits."""
    def __init__(self, period: float, t0: float, semimajor: float, eccen: float=0, inclination: float=90, lon_periapse: float=90):
        """Initialize an orbit object with the given orbital elements.

        Args:
            period: The orbital period.  Any unit may be used so long as it is used consistently.
            t0: The epoch time, when the orbit passes x=0 in the positive direction; same units as period.
            semimajor: The orbital semimajor axis.  Any unit may be used, but this sets the output units of
                the get_position function.  Usually users will wish to use units of stellar radius.
            eccen: The orbital eccentricity, it must be positive and less than 1, as this object cannot
                work with unbound orbits.
            inclination: The orbital inclination in degrees.  90 is an edge-on orbit, so transiting planets
                will typically be near this. i=0 is a clockwise orbit, starting from [0, a, 0] at t=0.
            lon_periapse: The longitude of the orbit's periapse.  A value of 90 places the periapse at
                [-a*(1-e), 0., 0.].
        """
    def get_position(self, t: float):
        """Calculates the position of the orbiting object at a given time.

        Args:
            t: The time to get the orbital position for.  The units must be the same as those used for
                `period` and `t0` on initialization.

        Returns:
            The position of the orbiting object at time t, as a one-dimensional numpy array of size 3.
        """
    @staticmethod
    def solve_kepler(mean_anomaly: float, eccen: float):
        """Solves the kepler equation for the true anomaly given the mean anomaly and eccentricity."""

@cython.cclass
class Shape:
    """A wrapper class for the C++ class Biellipsoid, with some added convenience functions.

    The biellipsoid consists of two tri-axial ellipsoids which share radii along the y and z axis
    but not necessarily the x axis, which are joined along the y-z plane, rotated arbitrarily, and
    then shifted to some position.

    For these calculations, three reference frames are used -- the conversion functions are exposed
    mainly for debugging purposes.  The frames are:

    :View Frame: This is the native frame users will be operating in. It is easiest to think of
        +x as being "right", +y as "up", and +z as "towards the viewer".
    :Aligned Frame: This is the frame in which the forward vector points in the +x,
        the up vector points in the +y, and the side vector points in the +z directions.  The
        rotation matrix of the biellipsoid rotates points from this frame to the view frame.
    :Sphere Frame: In this frame, the biellipsoid is a unit sphere.  This is a non-linear
        transform from the aligned frame, scaling y and z by r_up and r_side respectively,
        and x by r_forward or r_backward depending on whether x > 0.  Many geometric
        calculations amount to transforming to this frame, finding some point, line, or plane,
        and then transforming back to the view space.
    """
    cshape: cye.CShape

    @property
    def area(self):
        """The area of the shape in the view frame."""
    @property
    def r_forward(self):
        """The forward radius of the object; the +x direction for an identity rotation matrix."""
    @property
    def r_back(self):
        """The forward radius of the object; the -x direction for an identity rotation matrix."""
    @property
    def r_up(self):
        """The upward radius of the object; the y axis for an identity rotation matrix."""
    @property
    def r_side(self):
        """The upward radius of the object; the z axis for an identity rotation matrix."""
    @property
    def position(self):
        """The position of the center of the biellipsoid, as a numpy array."""
    @property
    def radii(self):
        """The forward, backward, up, and side radii of the bielipsoid, as a numpy array."""
    @property
    def rot(self):
        """The rotation matrix of the biellipsoid, a 3x3 numpy array, which transforms points
        from aligned to view space."""
    @property
    def forward(self):
        """The forward vector in view space."""
    @property
    def up(self):
        """The biellipsoid's up (along the poles) vector in view space."""
    @property
    def side(self):
        """The biellipsoid's side (forward cross up) vector in view space."""
    @property
    def limb_forward(self):
        """The ellipse defining the limb (visible edge) of the Biellipsoid on its forward half."""
    @property
    def limb_back(self):
        """The ellipse defining the limb (visible edge) of the Biellipsoid on its back half."""
    @property
    def joint(self):
        """The ellipse around the surface of the planet within the plane that joins the two
        half-ellipsoids that make up the biellipsoid."""
    def __init__(self, r_forward: float, r_back: float, r_up: float, r_side: float, theta: float=0, phi: float=0, gamma: float=0, ci: float=-2, x: float=0, y: float=0, z: float=0):
        """Define a biellipsoid in terms of it's origin position, rotation angles, and radii.

        Args:
            r_forward: The forward radius of the object -- along the +x direction for an identity
                rotation matrix.
            r_back: The forward radius of the object -- along the -x direction for an identity
                rotation matrix.
            r_up: The upward radius of the object -- along the y axis for an identity rotation
                matrix.
            r_side: The upward radius of the object -- along the z axis for an identity rotation
                matrix.
            theta: The counter-clockwise rotation of the biellipsoid around the z axis.
            phi: The counter-clockwise rotation of the biellipsoid around the y axis.
            gamma: The counter-clockwise rotation of the biellipsoid around the x axis.
            ci: The cosine of the inclination of the orbit.  This is used only to reorient the
                object along its orbit at the current position.  If the object should not be
                rotated with its current position, set as -2.
            x: The x position of the biellipsoid, in view space.
            y: The y position of the biellipsoid, in view space.
            z: The z position of the biellipsoid, in view space.
        """
    def set_rotation(self, theta: float, phi: float, gamma: float, ci: float=-2):
        """Sets the rotation of the biellipsoid to the new given values. The first three arguments
            are Euler angles around the z, y, and x axes respectively, applied in reverse order.
            If the final argument is between 0 and 1, the biellipsoid will further be rotated
            along its orbit.

        Args:
            theta: The counter-clockwise rotation of the biellipsoid around the z axis.
            phi: The counter-clockwise rotation of the biellipsoid around the y axis.
            gamma: The counter-clockwise rotation of the biellipsoid around the x axis.
            ci: The cosine of the inclination of the orbit.  This is used only to reorient the
                object along its orbit at the current position.  If the object should not be
                rotated with its current position, set as -2."""
    def set_position(self, x: float, y: float, z: float):
        """Set the position of the biellipsoid.  Note that this will not update the rotation of
        the object with its orbit; if this is desired, users should call set_rotation next."""
    def position_from_orbit(self, t: float, orb: Orbit, rotate_with_orbit: bool=False, origin=[0, 0, 0]): ...
    def is_visible(self, x: float, y: float, z: float):
        """Determines whether a the given point is 'visible' from the view plane; that is, whether
        a straight ray from the given point extending in the -z direction does NOT pass through
        the biellipsoid."""
    def is_forward(self, x: float, y: float, z: float):
        """Determines whether a point is on the forward half of the biellipsoid or the backwards
        half.  The point does not need to be on the surface of the biellipsoid, as it will be
        compared against the joining plane."""
    def is_forward_2d(self, x: float, y: float, local: cython.bint=False):
        """Determines whether the point closest to the viewer (lowest z) on the surface of the
        biellipsoid at [x, y] is on the forward half of the biellipsoid or the backwards half.
        This is similar to `is_forward` but is faster than using raycast to find the
        intersection point and subsequently call is_forward.

        Returns false if there are no points on the Biellipsoid at [x, y]."""
    def x_bounds(self):
        """Returns the maximum and minimum extent of the biellipsoid in the x direction."""
    def y_bounds(self):
        """Returns the maximum and minimum extent of the biellipsoid in the y direction."""
    def slice_ylimits(self, x: float):
        """For a given x, returns the largest and smallest values of y for which there is some z
        such that [x, y, z] is on the biellipsoid.  This is useful for computing integrals in
        view-space."""
    def line_intersects(self, x, y, ring_front: cython.bint=True):
        """Determines whether the line passing through [x, y, 0] in the +/-z direction passes
        through the biellipsoid."""
    def raycast(self, x: float, y: float): ...
    def world_to_aligned(self, loc): ...
    def world_to_sphere(self, loc): ...
    def aligned_to_world(self, loc): ...
    def aligned_to_sphere(self, loc): ...
    def sphere_to_world(self, loc): ...
    def sphere_to_aligned(self, loc): ...
    def principal_axes(self):
        """Get the principle axes from a biellipsoid, for visualization and testing purposes."""
    def meridians(self, axis=0, res=200):
        """Get the positions of the equator and 90-degree meridians on the biellipsoid."""
    def outline(self, res=200, yrange=False): ...
    def plot_ellipses(self, res=200, method='angles', f_args=dict(), b_args=dict()):
        """Similar to plot_outline, but plots each ellipse that makes up the bielipsoid's limb
        separately (including on the other ellipse's side), for debugging visualization purposes."""
    def plot_axes(self, colors=None, **args): ...
    def plot_outline(self, res=200, **args): ...
    def plot_area(self, res=200, **args): ...
    def plot_meridians(self, res=200, eq_args=dict(), prime_args=dict(), front_args=dict(), visible_only=True): ...

@cython.cclass
class LightSource:
    """Describes the emission of an object, so that the brightness at a given
    point can be quickly looked up. The source must be one of the following
    types, with the correct number of parameters provided:

    ``no_emission``
        0 parameters.  completely dark, always returns zero.

    ``lambertian``
        1 parameter: the brightness.  Uniform emission of light across the surface.

    ``quadratic_limb``
        3 parameters: the overall brightness and the two limb darkening
        coefficients.  A source with limb darkening using the quadratic functional form.

    ``nonlinear_limb``
        5 parameters: the overall brightness and four limb darkening
        coefficients.  A source with limb darkening using the nonlinear functional form.

    ``day_night``
        2 parameters: the day side brightness and the night-side brightness. What
        it says on the tin, but note that this is much more efficient than an emission map.

    ``emission map``
        2 parameters: the azimuthal and longitudinal resolution of the grid.
        Interpolates the brightness on a grid of values provided by the user.  Extremely general,
        but much slower than other methods. Default grid values are zero, the user must set them
        by calling :func:`eggman.LightSource.set_emission_map`.

    Note that brightnesses are before accounting for surface area, so that e.g. the total
    apparent brightness of a lambertian unit sphere is 2*pi*brightness.
    """
    csource: cye.LightSource
    _source_type_names_ = ['no_emission', 'lambertian', 'quadratic_limb', 'nonlinear_limb', 'day_night', 'emission_map']
    _source_n_params_ = [0, 1, 3, 5, 2, 2]
    _source_enum_ = [SourceType.NoEmission, cye.SourceType.Lambertian, cye.SourceType.QuadraticLimb, cye.SourceType.NonLinearLimb, cye.SourceType.DayNight, cye.SourceType.EmissionMap]

    @property
    def source_type(self):
        """The type of the source as a string."""
    @property
    def source_type_code(self):
        """The type of the source as an integer."""
    @property
    def source_params(self):
        """The parameters of the source (e.g. limb darkening parameters)."""
    @property
    def limb_norm(self):
        """The normalization constant of the source."""
    @property
    def n(self):
        """The number of points along the longitudinal axis defining the emission map (-1 if this
        source does not use an emission map)."""
    @property
    def m(self):
        """The number of points along the latitudinal axis defining the emission map, not including
        the two poles (-1 if this source does not use an emission map)."""
    @property
    def map_size(self):
        """The total number of points in of the emission map, equal to m*n + 2."""
    def __init__(self, source_type: str, source_params: list[float]):
        """Create a new source object with the given type and parameters.

        Args:
            source_type: a string descrubing the type of source to use. See class documentation
                for the list of valid options.
            source_params: a list or array of parameters of the source. See class documentation
                for how many params are required for each type.
        """
    def get_brightness(self, x, y, bell: Shape, ring_front: cython.bint=True): ...
    def get_brightness_sphere(self, x, y): ...
    def get_emission_point(self, i: int) -> float:
        """Get the value of the emission map's i'th grid point.

        Args:
            i: the index of the point.  Must be an int between 0 and ``map_size``.

        Returns: The value of the i'th grid point as a float.
        """
    def set_emission_point(self, i: int, value: float) -> None:
        """Set the value of the i'th emission_map grid point.

        Args:
            i: the index of the point.  Must be an int between 0 and ``map_size``.
            value: the new value for that grid point, as a float.
        """
    def get_emission_location(self, i: int) -> np.ndarray:
        """Get the location on the unit sphere corresponding to the i'th emission_map grid point.

        Args:
            i: the index of the point.  Must be an int between 0 and ``map_size``.

        Returns: a 1-d numpy array of size 3 containing the x, y, and z coordinates of the
            requested point.  This vector always has a length of 1.
        """
    def set_emission_map(self, func: typing.Callable) -> np.ndarray:
        """Set the emission map using an emission mapping function.

        Args:
            func: a function that maps locations on the unit sphere to brightness values.  It
            should accept 3 arguments (x, y, and z coordinates) and return a single float.

        Returns: An array of the values computed from the function at the grid points.
        """
    def interp_emission(self, x: float, y: float, z: float) -> float:
        """Interpolate the emission map at the given (x, y, z) coordinates.

        Note that the coordinates provided will be clamped onto the surface of the unit sphere in
        cylindrical coordinates (not spherical), with y as the up-down direction.

        Args:
            x: the first coordinate point to interpolate on.
            y: the second coordinate point to interpolate on, which will be clamped to [-1, 1].
            z: the third coordinate point to interpolate on.

        Returns: The interpolated value as a float.
        """
    def plot_brightness(self, shp: Shape, res=400, axis=None, ring_front: cython.bint=True, **args): ...

@cython.cclass
class Ellipse:
    """An ellipse centered at the origin, defined by two conjugate diameters e1 and e1."""
    @property
    def e1(self):
        """The first of the two conjugate diameters that define the ellipse."""
    @property
    def e2(self):
        """The second of the two conjugate diameters that define the ellipse."""
    @property
    def det(self):
        """The determinant of the matrix of conjugate diameters (with the third dimension dropped)."""
    @property
    def x_size(self):
        """The on-sky half-width of the ellipse."""
    @property
    def y_size(self):
        """The on-sky half-height of the ellipse."""
    def __init__(self, e1, e2):
        """Define an ellipse in terms of its conjugate diameters.

        Args:
            e1: The first conjugate diameter (a 1-d array of length 3).
            e2: The second conjugate diameter (a 1-d array of length 3).
        """
    @classmethod
    def create_from_rot_radii(cls, a: float, b: float, rot: np.ndarray):
        """Define an ellipse in terms of a rotation matrix and its semimajor and semiminor axes.

        Args:
            a: The semimajor axis of the ellipse.
            b: The semiminor axis of the ellipse.
            rot: A 3x3 rotation matrix to apply to the Ellipse.
        """
    def get_ybounds(self, x: float):
        """The upper and lower bounding points of the intersection of the ellipse and the plane
        defined by the given x.

        Args:
            x: The x value to find the y-bounds for.

        Returns:
            A 2x3 array representing the min and max bounds of the intersection.  If there is
            no intsersection, the array is filled with nans."""
    def line_intersects(self, x: float, y: float) -> tuple[cython.bint, np.ndarray]:
        """Checks whether a line across z at (x, y) passes through the ellipse.

        Args:
            x: the x position of the line to check for an intersection.
            y: the y position of the line to check for an intersection.

        Returns: A tuple with two components, a bool indicating whether the line
            intersects the ellipsoid and a length-3 Numpy array representing
            the point of intersection (nans if there wasn't one).
        """
    def nearest_to_line(self, xt: float, yt: float):
        """Locate the point on the ellipse nearest to the line xt, yt."""
    def outline(self, res=200, dir: Optional[np.ndarray] | None=None, method: str='angles'):
        """Generates an array of points along the ellipse."""
    def plot_outline(self, res=200, origin=(0.0, 0.0), dir=None, method='angles', **args):
        """Plots the ellipse in the x-y plane (ignores z)."""
    def plot_vectors(self, origin=(0.0, 0.0), **args):
        """Plots the conjugate diameters of the ellipse in the x-y plane."""

@cython.cclass
class PlanetSystem:
    cps: cye.CPlanetSystem

    def __init__(self, atol=1e-06, rtol=0.001, max_steps=100):
        """Initialize a PlanetSystem with the integration tolerances.

        Args:
            atol: the absolute tolerance for the integrators.
            rtol: the tolerance for the integrators relative to the result."""
    def add_object(self, orbit: Orbit, shape: Shape, source: LightSource, rotate_with_orbit: cython.bint=False, parent_index: int=-1):
        """Adds an object of the given specifications to the system.

        Args:
            orbit: An Orbit object describing the orbit of the object being added.
            shape: A Shape object describing the shape of the object being added.
            source: A LightSource object describing the emission of the object.
            rotate_with_orbit: whether or not the object rotates as it moves through its orbit
                (tidally locked to the parent or origin).
            parent_index: The index of a previously added object that the new object should orbit
                (like a moon or ring); if negative, the new object orbits the origin.
        """
    def add_planet(self, r_forward: float, r_back: float, r_up: float, r_side: float, period: float, semimajor: float, t0: float=0, eccen: float=0, inclination: float=90, lon_periapse: float=90.0, theta: float=0, phi: float=0, gamma: float=0, source: LightSource | None=None, rotate_with_orbit: cython.bint=True, parent_index: int=-1):
        """Adds a planet of the given specifications to the system.  This is a wrapper for
            add_object, whose arguments are passed through to Shape and Orbit.

        Args:
            r_forward: The forward radius of the object -- along the +x direction for an identity
                rotation matrix.
            r_back: The forward radius of the object -- along the -x direction for an identity
                rotation matrix.
            r_up: The upward radius of the object -- along the y axis for an identity rotation
                matrix.
            r_side: The upward radius of the object -- along the z axis for an identity rotation
                matrix.
            period: The orbital period.  Any unit may be used so long as it is used consistently.
            semimajor: The orbital semimajor axis.  Any unit may be used, but this sets the output
                units of the get_position function.  Usually users will wish to use units of
                stellar radius.
            t0: The epoch time, when the orbit passes x=0 in the positive direction; must have the
                same units as period.
            eccen: The orbital eccentricity, it must be positive and less than 1, as this object
                cannot work with unbound orbits.
            inclination: The orbital inclination in degrees.  90 is an edge-on orbit, so transiting
                planets will typically be near this. i=0 is a clockwise orbit, starting from
                [0, a, 0] at t=0.
            lon_periapse: The longitude of the orbit's periapse.  A value of 90 places the periapse
                at [-a*(1-e), 0., 0.].
            theta: The counter-clockwise rotation of the biellipsoid around the z axis.
            phi: The counter-clockwise rotation of the biellipsoid around the y axis.
            gamma: The counter-clockwise rotation of the biellipsoid around the x axis.
            source: A LightSource object describing the emission of the object.
            rotate_with_orbit: whether or not the object rotates as it moves through its orbit
                (tidally locked to the parent or origin).
            parent_index: The index of a previously added object that the new object should orbit
                (like a moon); if negative, the new object orbits the origin."""
    def add_star(self, limb_type: str, limb_params: list[float]):
        """Adds a star to the system.  This is a wrapper for add_object, and places a unit-sphere
            at the origin.

        Args:
            limb_type: A string indicating the type of limb darkening of the star.  Should be one
                of "lambertian" (flat), "quadratic_limb", or "nonlinear_limb".
            limb_params: A list of floats representing the parameters of the limb darkening, whose
                length depends on the limb type (0, 2, and 4 respectively from the above list).  If
                provided, an additional parameter at the start sets the overall brightness
                (1/pi results in a total luminosity of 1, and so is the default)."""
    def add_ring(self, r_outer: float, r_inner: float, parent_index: int, theta: float=0, phi: float=0, gamma: float=0):
        """Adds a ring around the given object. With rotations set to zero, the ring is face-on.
        This is a wrapper for add_object, whose arguments are passed through to Shape and Orbit.

        Args:
            r_outer: The outer radius of the ring.
            r_inner: The inner radius of the ring, that is, within this radius the ring will not
                block any light.  This should be large enough that it is not touching the
                parent object if the latter is emissive.
            theta: The counter-clockwise rotation of the ring around the z axis.
            phi: The counter-clockwise rotation of the ring around the y axis.
            gamma: The counter-clockwise rotation of the ring around the x axis.
            parent_index: The index of the object to place a ring around."""
    def set_time(self, t: float) -> None:
        """Sets the time of the system, moving the objects into position based on their orbits.
            This is automatically called in phase_curve_integral but can be useful for debugging
            and with plot_objects.

        Args:
            t: the time, in the same units as the period and epoch time t0 specified in the Orbit
                objects."""
    def integrate_single(self, i: int) -> float:
        """Get the brightness of a single target at the current time (set by set_time,
            defaulted to 0.)

        Args:
            i: Which object to get the brightness of -- these are indexed increasing from 0 in
                order of insertion.

        Returns:
            The brightness constribution of the requested object, accounting for other objects
            that obscure it.
        """
    def integrate(self, times: cye.Array1d_f64):
        """Get the brightness of all objects in the system, added together, at the given times.
            This is the standard function to call for getting a light curve.

        Args:
            times: A numpy array of times to calculate for, in the same units as periods and epoch
                time t0 specified in the orbits.

        Returns:
            A Numpy array of total brightnesses at the specified times."""
    def get_n_objects(self) -> int:
        """Returns the number of objects that have been successfully inserted so far."""
    def clear_objects(self) -> None:
        """Deletes all the objects so far added, starting over from scratch.  This is slightly
        faster than creating a new object."""
    def __getitem__(self, i: int) -> tuple[Orbit, Shape, LightSource, bool]:
        """Get an object previously added to the system.

        Args:
            i: The index of the object, which were set in order of insertion starting from 0.

        Returns:
            A tuple of an OrbitWrap, Shape, LightSource, and bool object that describing the i'th
                object -- the final bool is whether the object rotates with its orbit.
        """
    def plot_objects(self, res=200, axis=None, arg_list=list(), **kwargs):
        """Create a simple plot of the system using matplotlib, at the current time (set by
            set_time or 0 by default), using matplotlib.pcolormesh.

        Args:
            res: The resolution to plot the objects at, as an integer.
            axis: The matplotlib axis object to plot on.  If left as the default None, new axes
                will be created.
            arg_list: A list of dictionaries containing keyword arguments to pass to
                pyplot.pcolormesh. for each object in the system in order.  These settings override
                global settings from `kwargs`.
            kwargs: Additional keyword arguments to be passed to pyplot.pcolormesh for all objects
                in the system, unless overridden by arg_list."""

class Mat3(TypedDict):
    xx: float
    xy: float
    xz: float
    yx: float
    yy: float
    yz: float
    zx: float
    zy: float
    zz: float

class Vec3(TypedDict):
    x: float
    y: float
    z: float

class Bounds(TypedDict):
    min: float
    max: float

def asymmetricTransit(rMorning: float, rEvening: float, rPole: float, t: numpy.typing.NDArray[numpy.double], t0: float, period: float, semimajor: float, inclination: float, limbType: str, limb: object, eccen: float=0, lonPeriapse: float=90.0, theta: float=0.0, atol: float=1e-06, rtol: float=0.001, max_steps: int=200) -> object:
    """Calculates the transit of a piecewise-elliptical planet.  Assumes the same projected shape regardless of its position
    in the orbit.  Uses the same model as catwoman (two spheres split down the middle) if rPole is negative.

    Args:
        rMorning: The radius of the planet at the morning (right) side of the planet at the equator relative to the stellar radius.
        rEvening: The radius of the planet at the evening (left) side of the planet at the equator relative top the stellar radius.
        rPole: The radius of the planet at the poles (top and bottom) relative to the stellar radius.  If -1, rPole is set to rMorning one morning side and rEvening on the evening side.
        t: A 1-d Numpy array of observation times to be simulated (must be the same unit as t0 and period).
        t0: The time of a mid-transit (needn't be the observed one).
        period: The orbital period of the planet.
        semimajor: The semimajor axis of the planet relative to the stellar radius.
        inclination: The inclination of the orbit in degrees (near 90 for transiting planets).
        limbType: The type of limb darkening to use: `quadratic` or `nonlinear`.
        limb: An iterable of limb darkening parameters, length 2 for quadratic and 4 for nonlinear.
        eccen: The orbital eccentricity of the planet.  Must be 0 <= e < 1, defaults to zero.
        lonPeriapse: The longitude of the periapse of the planet's orbit in degrees.  The default of 90 means the pariapse occurs at mid-transit.
        theta: The angle to rotate the planet by on-sky in the counter-clockwise direction.
        atol: The absolute tolerance for the integration results.
        rtol: The relative tolerance for the integration results.
        max_steps: The maximum number of steps to use in integration; if this is exceeded, an error is printed and nan is returned.

    Returns:
        The relative flux from the star at the time given, so 1 if the planet is out of transit.
    """
